# Copyright 2018 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

# Use this docker-compose file together with sawtoth-pdo.yaml to build in debug mode
# and enable debugging with gdb/sgx-gdb and alike ...


version: "2.1"

services:

  # PDO EHS, PS and client ...
  pdo-build:
    # Note: the default entrypoint will result in zombie processes when daemons such as ps-start/es-start terminate
    # as the shell doesn't clean up, which will make run-tests fail!. Changing entrypoint to bash solves that but
    # alas this doesn't not work in general here as it makes docker-compse up fail for this combponent and has to be done
    # on individual basis
    build:
      args:
        PDO_DEBUG_BUILD: 1
    environment:
      - PDO_DEBUG_BUILD=1
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_PTRACE

  # PDO Transaction processor
  pdo-tp-ccf:
    environment:
      - PDO_DEBUG_BUILD=1
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_PTRACE
